
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE SCHEMA IF NOT EXISTS "public";

ALTER SCHEMA "public" OWNER TO "pg_database_owner";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."contacttype" AS ENUM (
    'staff',
    'customer',
    'dealer'
);

ALTER TYPE "public"."contacttype" OWNER TO "postgres";

CREATE TYPE "public"."gendertype" AS ENUM (
    'male',
    'female'
);

ALTER TYPE "public"."gendertype" OWNER TO "postgres";

CREATE TYPE "public"."infotype" AS ENUM (
    'personal',
    'corporate'
);

ALTER TYPE "public"."infotype" OWNER TO "postgres";

CREATE TYPE "public"."salesstatus" AS ENUM (
    'in-progress',
    'paid',
    'refunded'
);

ALTER TYPE "public"."salesstatus" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."contacts" (
    "id" integer NOT NULL,
    "contact_type" "public"."contacttype" DEFAULT 'customer'::"public"."contacttype" NOT NULL,
    "location_id" integer,
    "profile_url" "text" DEFAULT ''::"text" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "info_type" "public"."infotype" DEFAULT 'personal'::"public"."infotype" NOT NULL,
    "middle_initial" character(2),
    "price_level" integer DEFAULT 0 NOT NULL,
    "address_line" "text" NOT NULL,
    "birthdate" timestamp without time zone,
    "birthplace" "text",
    "sex" "public"."gendertype" DEFAULT 'male'::"public"."gendertype" NOT NULL,
    "citizenship" "text" DEFAULT 'Filipino'::"text",
    "civil_status" "text",
    "occupation" "text",
    "tin_no" "text",
    "company_name" "text",
    "company_address" "text",
    "business_nature" "text",
    "date_added" timestamp without time zone DEFAULT "now"() NOT NULL,
    "date_open" timestamp without time zone NOT NULL,
    "approved_by" integer,
    "remarks" "text" DEFAULT ''::"text"
);

ALTER TABLE "public"."contacts" OWNER TO "postgres";

ALTER TABLE "public"."contacts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contacts_id_seq"
    START WITH 10000
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."invoice_types" (
    "id" integer NOT NULL,
    "invoice_name" "text" NOT NULL,
    "code" "text" NOT NULL
);

ALTER TABLE "public"."invoice_types" OWNER TO "postgres";

ALTER TABLE "public"."invoice_types" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."invoice_types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."item_types" (
    "id" integer NOT NULL,
    "class" "text" NOT NULL
);

ALTER TABLE "public"."item_types" OWNER TO "postgres";

ALTER TABLE "public"."item_types" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."item_types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."items" (
    "id" integer NOT NULL,
    "staff_id" integer,
    "dealer_id" integer NOT NULL,
    "item_type_id" integer,
    "item_image_url" "text" DEFAULT ''::"text" NOT NULL,
    "item_name" "text" NOT NULL,
    "item_cost" numeric NOT NULL,
    "item_unit_type" character(4) DEFAULT 'pcs'::"bpchar" NOT NULL,
    "item_quantity" numeric DEFAULT 0 NOT NULL,
    "code" "text" NOT NULL,
    "barcode" "text",
    "unit" character(3) NOT NULL
);

ALTER TABLE "public"."items" OWNER TO "postgres";

ALTER TABLE "public"."items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."items_id_seq"
    START WITH 20000
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."items_price_levels" (
    "id" integer NOT NULL,
    "price_level_id" integer NOT NULL,
    "item_id" integer NOT NULL
);

ALTER TABLE "public"."items_price_levels" OWNER TO "postgres";

ALTER TABLE "public"."items_price_levels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."items_price_levels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."locations" (
    "id" integer NOT NULL,
    "location_name" "text" NOT NULL
);

ALTER TABLE "public"."locations" OWNER TO "postgres";

ALTER TABLE "public"."locations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."locations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."price_levels" (
    "id" integer NOT NULL,
    "level_name" "text" NOT NULL,
    "code" "text" NOT NULL,
    "price" numeric DEFAULT 0 NOT NULL
);

ALTER TABLE "public"."price_levels" OWNER TO "postgres";

ALTER TABLE "public"."price_levels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."price_levels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."sales" (
    "id" integer NOT NULL,
    "user_id" "uuid",
    "staff_id" integer,
    "customer_id" integer,
    "dealer_id" integer,
    "invoice_type_id" integer,
    "invoice_no" integer DEFAULT 0 NOT NULL,
    "sales_date" timestamp without time zone DEFAULT "now"() NOT NULL,
    "sub_total" numeric DEFAULT 0 NOT NULL,
    "total_due" numeric DEFAULT 0 NOT NULL,
    "tendered_amount" numeric DEFAULT 0 NOT NULL,
    "amount_paid" numeric DEFAULT 0 NOT NULL,
    "change_due" numeric DEFAULT 0 NOT NULL,
    "is_cancelled" boolean DEFAULT false NOT NULL,
    "sales_status" "public"."salesstatus" DEFAULT 'in-progress'::"public"."salesstatus" NOT NULL,
    "discount_amount" numeric DEFAULT 0 NOT NULL,
    "tax_amount" numeric DEFAULT 0 NOT NULL,
    "cash_amount" numeric DEFAULT 0 NOT NULL,
    "payment_method" "text" DEFAULT 'cash'::"text" NOT NULL
);

ALTER TABLE "public"."sales" OWNER TO "postgres";

ALTER TABLE "public"."sales" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sales_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."selections" (
    "id" integer NOT NULL,
    "sales_id" integer NOT NULL,
    "item_id" integer,
    "price_level_id" integer,
    "quantity" integer DEFAULT 1 NOT NULL,
    "cost" numeric DEFAULT 0 NOT NULL,
    "price" numeric DEFAULT 0 NOT NULL,
    "total_price" numeric DEFAULT 0 NOT NULL,
    "total_quantity" numeric DEFAULT 1 NOT NULL
);

ALTER TABLE "public"."selections" OWNER TO "postgres";

ALTER TABLE "public"."selections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."selections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."contacts"
    ADD CONSTRAINT "contacts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."invoice_types"
    ADD CONSTRAINT "invoice_types_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."item_types"
    ADD CONSTRAINT "item_types_class_key" UNIQUE ("class");

ALTER TABLE ONLY "public"."item_types"
    ADD CONSTRAINT "item_types_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_code_key" UNIQUE ("code");

ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_item_name_key" UNIQUE ("item_name");

ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."items_price_levels"
    ADD CONSTRAINT "items_price_levels_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."locations"
    ADD CONSTRAINT "locations_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."price_levels"
    ADD CONSTRAINT "price_levels_code_key" UNIQUE ("code");

ALTER TABLE ONLY "public"."price_levels"
    ADD CONSTRAINT "price_levels_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."selections"
    ADD CONSTRAINT "selections_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."contacts"
    ADD CONSTRAINT "contacts_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "public"."contacts"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."contacts"
    ADD CONSTRAINT "contacts_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_dealer_id_fkey" FOREIGN KEY ("dealer_id") REFERENCES "public"."contacts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_item_type_id_fkey" FOREIGN KEY ("item_type_id") REFERENCES "public"."item_types"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."items_price_levels"
    ADD CONSTRAINT "items_price_levels_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."items_price_levels"
    ADD CONSTRAINT "items_price_levels_price_level_id_fkey" FOREIGN KEY ("price_level_id") REFERENCES "public"."price_levels"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "public"."contacts"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."contacts"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_dealer_id_fkey" FOREIGN KEY ("dealer_id") REFERENCES "public"."contacts"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_invoice_type_id_fkey" FOREIGN KEY ("invoice_type_id") REFERENCES "public"."invoice_types"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "public"."contacts"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."selections"
    ADD CONSTRAINT "selections_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."selections"
    ADD CONSTRAINT "selections_price_level_id_fkey" FOREIGN KEY ("price_level_id") REFERENCES "public"."price_levels"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."selections"
    ADD CONSTRAINT "selections_sales_id_fkey" FOREIGN KEY ("sales_id") REFERENCES "public"."sales"("id") ON DELETE CASCADE;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."contacts" TO "anon";
GRANT ALL ON TABLE "public"."contacts" TO "authenticated";
GRANT ALL ON TABLE "public"."contacts" TO "service_role";

GRANT ALL ON SEQUENCE "public"."contacts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contacts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contacts_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."invoice_types" TO "anon";
GRANT ALL ON TABLE "public"."invoice_types" TO "authenticated";
GRANT ALL ON TABLE "public"."invoice_types" TO "service_role";

GRANT ALL ON SEQUENCE "public"."invoice_types_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."invoice_types_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."invoice_types_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."item_types" TO "anon";
GRANT ALL ON TABLE "public"."item_types" TO "authenticated";
GRANT ALL ON TABLE "public"."item_types" TO "service_role";

GRANT ALL ON SEQUENCE "public"."item_types_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."item_types_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."item_types_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."items" TO "anon";
GRANT ALL ON TABLE "public"."items" TO "authenticated";
GRANT ALL ON TABLE "public"."items" TO "service_role";

GRANT ALL ON SEQUENCE "public"."items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."items_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."items_price_levels" TO "anon";
GRANT ALL ON TABLE "public"."items_price_levels" TO "authenticated";
GRANT ALL ON TABLE "public"."items_price_levels" TO "service_role";

GRANT ALL ON SEQUENCE "public"."items_price_levels_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."items_price_levels_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."items_price_levels_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."locations" TO "anon";
GRANT ALL ON TABLE "public"."locations" TO "authenticated";
GRANT ALL ON TABLE "public"."locations" TO "service_role";

GRANT ALL ON SEQUENCE "public"."locations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."locations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."locations_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."price_levels" TO "anon";
GRANT ALL ON TABLE "public"."price_levels" TO "authenticated";
GRANT ALL ON TABLE "public"."price_levels" TO "service_role";

GRANT ALL ON SEQUENCE "public"."price_levels_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."price_levels_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."price_levels_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."sales" TO "anon";
GRANT ALL ON TABLE "public"."sales" TO "authenticated";
GRANT ALL ON TABLE "public"."sales" TO "service_role";

GRANT ALL ON SEQUENCE "public"."sales_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sales_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sales_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."selections" TO "anon";
GRANT ALL ON TABLE "public"."selections" TO "authenticated";
GRANT ALL ON TABLE "public"."selections" TO "service_role";

GRANT ALL ON SEQUENCE "public"."selections_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."selections_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."selections_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
